### ISSUE TITLE
Use new info dicts for GOTO dashboard

### ISSUE THREAD

**Issue by martinjohndyer** [warwick-one-metre/dashboard#14]
GOTO-OBS/g-tecs#161 is solved by GOTO-OBS/g-tecs#208 adding new `get_info_simple()` commands, specifically for the dashboard.

Hopefully it should be simple enough to replace `d.get_info()` with the new version.

https://github.com/warwick-one-metre/dashboard/blob/f857d486fc889f2fb66a250efb4cf413181f80f4/update-dashboard-data#L79-L87

**Comment by pchote** [comment]
This is now mostly done, but i've had to disable the cam query because it generates an error and breaks the exposure queue (https://github.com/GOTO-OBS/g-tecs/issues/214).  I'll leave this open until we can reenable that query.

**Comment by pchote** [comment]
Superseded by #24.
